// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/scienceandcode/habits-todo-backend/internal/api/controller"
	"github.com/scienceandcode/habits-todo-backend/internal/api/service"
	di2 "github.com/scienceandcode/habits-todo-backend/internal/api/service/di"
	"github.com/scienceandcode/habits-todo-backend/internal/db"
	"github.com/scienceandcode/habits-todo-backend/internal/repository/di"
	"github.com/scienceandcode/habits-todo-backend/internal/server"
)

// Injectors from wire.go:

func InitializeHttpServer() *server.HttpServer {
	healthService := service.NewHealthService()
	healthController := controller.NewHealthController(healthService)
	googleAuthService := service.NewGoogleAuthService()
	googleAuthController := controller.NewGoogleAuthController(googleAuthService)
	gormDB := db.GetConnection()
	userRepository := di.ProvideUserRepository(gormDB)
	jwtService := di2.ProvideJWTService()
	userAuthService := service.NewUserAuthService(userRepository, jwtService)
	userAuthController := controller.NewUserAuthController(userAuthService)
	userService := service.NewUserService(userRepository)
	userController := controller.NewUserController(userService)
	httpServer := server.NewHttpServer(healthController, googleAuthController, userAuthController, userController)
	return httpServer
}
